const defaultCategories = [
  "Все",
  "Новинки и Акции",
  "Популярное",
  "Напитки",
  "Готовая еда",
  "Десерты",
];

const defaultPageData = {
  categories: defaultCategories,
  featuredProducts: [
    {
      id: 1,
      title: "Фирменный бургер",
      price: 299,
      meta: "260 г",
      description: "Сочный бифштекс, сыр чеддер и свежие овощи.",
      details: "420 ккал · 15-20 мин",
      accent: "burger",
      emoji: "🍔",
    },
    {
      id: 2,
      title: "Капучино средний",
      price: 179,
      meta: "300 мл",
      description: "100% арабика и плотная молочная пенка.",
      details: "160 ккал · 10-15 мин",
      accent: "coffee",
      emoji: "☕",
    },
  ],
  promoProducts: [
    {
      id: 3,
      title: "Комбо дня",
      price: 459,
      meta: "1 шт",
      description: "Бургер, картофель фри и напиток.",
      details: "690 ккал · 15-25 мин",
      accent: "combo",
      emoji: "🍟",
      badge: "Выгодно",
    },
  ],
};

const restaurantPageDataById = {
  1: {
    categories: ["Все", "Новинки и Акции", "Популярное", "Напитки", "Бургеры", "Картофель"],
    featuredProducts: [
      {
        id: 101,
        title: "Гранд де Люкс",
        price: 334,
        meta: "255 г",
        description: "Двойная говядина, фирменный соус и маринованные огурцы.",
        details: "540 ккал · 15-20 мин",
        accent: "burger",
        emoji: "🍔",
      },
      {
        id: 102,
        title: "Флэт Уайт средний",
        price: 170,
        meta: "300 мл",
        description: "Эспрессо на двойной порции с бархатным молоком.",
        details: "180 ккал · 10-15 мин",
        accent: "coffee",
        emoji: "☕",
      },
      {
        id: 103,
        title: "Праздничный комбо",
        price: 590,
        meta: "1 шт",
        description: "Бургер, фри и напиток в одном наборе.",
        details: "760 ккал · 15-25 мин",
        accent: "combo",
        emoji: "🍟",
        badge: "Носки в подарок",
      },
    ],
    promoProducts: [
      {
        id: 104,
        title: "Комбо Вкусно и точка",
        price: 429,
        meta: "1 шт",
        description: "Классический бургер, картофель и кола.",
        details: "650 ккал · 15-20 мин",
        accent: "combo-light",
        emoji: "🥤",
      },
      {
        id: 105,
        title: "Картофель фри",
        price: 99,
        meta: "120 г",
        description: "Хрустящий картофель с солью.",
        details: "330 ккал · 10-15 мин",
        accent: "fries",
        emoji: "🍟",
      },
      {
        id: 106,
        title: "Наггетсы",
        price: 149,
        meta: "6 шт",
        description: "Нежное куриное филе в панировке.",
        details: "290 ккал · 10-15 мин",
        accent: "nuggets",
        emoji: "🍗",
      },
    ],
  },
  2: {
    categories: ["Все", "Популярное", "Бургеры", "Закуски", "Соусы", "Напитки"],
    featuredProducts: [
      {
        id: 201,
        title: "Воппер",
        price: 309,
        meta: "280 г",
        description: "Бургер на огне с томатами и салатом айсберг.",
        details: "670 ккал · 15-20 мин",
        accent: "burger",
        emoji: "🍔",
      },
      {
        id: 202,
        title: "Чизбургер",
        price: 159,
        meta: "140 г",
        description: "Классика с сыром чеддер и кетчупом.",
        details: "340 ккал · 10-15 мин",
        accent: "combo-light",
        emoji: "🧀",
      },
      {
        id: 203,
        title: "Кинг Комбо",
        price: 499,
        meta: "1 набор",
        description: "Воппер, фри и пепси.",
        details: "820 ккал · 15-25 мин",
        accent: "combo",
        emoji: "🥤",
        badge: "-20%",
      },
    ],
    promoProducts: [
      {
        id: 204,
        title: "Луковые кольца",
        price: 139,
        meta: "8 шт",
        description: "Подаются с сырным соусом.",
        details: "300 ккал · 10-15 мин",
        accent: "nuggets",
        emoji: "🧅",
      },
      {
        id: 205,
        title: "Картофель по-деревенски",
        price: 129,
        meta: "130 г",
        description: "Картофельные дольки со специями.",
        details: "360 ккал · 10-15 мин",
        accent: "fries",
        emoji: "🥔",
      },
      {
        id: 206,
        title: "Милкшейк ванильный",
        price: 199,
        meta: "400 мл",
        description: "Густой молочный коктейль.",
        details: "410 ккал · 10-15 мин",
        accent: "coffee",
        emoji: "🥛",
      },
    ],
  },
  3: {
    categories: ["Все", "Завтраки", "Кофе", "Сэндвичи", "Десерты", "Новинки"],
    featuredProducts: [
      {
        id: 301,
        title: "Круассан с ветчиной",
        price: 249,
        meta: "180 г",
        description: "Слоеный круассан с сыром и ветчиной.",
        details: "390 ккал · 15-20 мин",
        accent: "combo-light",
        emoji: "🥐",
      },
      {
        id: 302,
        title: "Раф кофе",
        price: 229,
        meta: "300 мл",
        description: "Сливочный раф с ванильным сиропом.",
        details: "280 ккал · 10-15 мин",
        accent: "coffee",
        emoji: "☕",
      },
      {
        id: 303,
        title: "Чизкейк Нью-Йорк",
        price: 269,
        meta: "130 г",
        description: "Нежный десерт на песочной основе.",
        details: "360 ккал · 10-15 мин",
        accent: "combo",
        emoji: "🍰",
      },
    ],
    promoProducts: [
      {
        id: 304,
        title: "Сырники со сметаной",
        price: 299,
        meta: "220 г",
        description: "Творожные сырники с ягодным соусом.",
        details: "430 ккал · 15-20 мин",
        accent: "nuggets",
        emoji: "🧁",
      },
      {
        id: 305,
        title: "Сэндвич с лососем",
        price: 349,
        meta: "210 г",
        description: "Слабосоленый лосось и творожный сыр.",
        details: "390 ккал · 15-20 мин",
        accent: "burger",
        emoji: "🥪",
      },
      {
        id: 306,
        title: "Лимонад маракуйя",
        price: 189,
        meta: "400 мл",
        description: "Освежающий лимонад со льдом.",
        details: "170 ккал · 10-15 мин",
        accent: "combo-light",
        emoji: "🍹",
      },
    ],
  },
  4: {
    categories: ["Все", "Суши", "Роллы", "Пицца", "Wok", "Напитки"],
    featuredProducts: [
      {
        id: 401,
        title: "Филадельфия классик",
        price: 469,
        meta: "8 шт",
        description: "Лосось, сливочный сыр и рис.",
        details: "520 ккал · 25-35 мин",
        accent: "combo",
        emoji: "🍣",
      },
      {
        id: 402,
        title: "Пицца Пепперони",
        price: 589,
        meta: "30 см",
        description: "Тонкое тесто, моцарелла и пепперони.",
        details: "980 ккал · 25-35 мин",
        accent: "burger",
        emoji: "🍕",
      },
      {
        id: 403,
        title: "Удон с курицей",
        price: 379,
        meta: "320 г",
        description: "Лапша удон в соусе терияки.",
        details: "640 ккал · 20-30 мин",
        accent: "nuggets",
        emoji: "🍜",
      },
    ],
    promoProducts: [
      {
        id: 404,
        title: "Сет Запеченный",
        price: 899,
        meta: "24 шт",
        description: "Три вида запеченных роллов.",
        details: "1200 ккал · 30-40 мин",
        accent: "combo-light",
        emoji: "🍱",
        badge: "Хит",
      },
      {
        id: 405,
        title: "Мисо суп",
        price: 219,
        meta: "300 мл",
        description: "Легкий суп с тофу и водорослями.",
        details: "140 ккал · 15-20 мин",
        accent: "coffee",
        emoji: "🥣",
      },
      {
        id: 406,
        title: "Морс клюквенный",
        price: 139,
        meta: "500 мл",
        description: "Домашний морс без газа.",
        details: "110 ккал · 10-15 мин",
        accent: "fries",
        emoji: "🧃",
      },
    ],
  },
  5: {
    categories: ["Все", "Пицца", "Закуски", "Комбо", "Десерты", "Напитки"],
    featuredProducts: [
      {
        id: 501,
        title: "Пепперони 30 см",
        price: 639,
        meta: "1 шт",
        description: "Острая колбаска и сыр моцарелла.",
        details: "1050 ккал · 25-35 мин",
        accent: "burger",
        emoji: "🍕",
      },
      {
        id: 502,
        title: "Супер Папа 30 см",
        price: 729,
        meta: "1 шт",
        description: "Мясная пицца с беконом и ветчиной.",
        details: "1180 ккал · 25-35 мин",
        accent: "combo",
        emoji: "🍕",
      },
      {
        id: 503,
        title: "Куриные крылья",
        price: 329,
        meta: "8 шт",
        description: "Крылышки с барбекю-соусом.",
        details: "560 ккал · 20-30 мин",
        accent: "nuggets",
        emoji: "🍗",
      },
    ],
    promoProducts: [
      {
        id: 504,
        title: "Сырные палочки",
        price: 269,
        meta: "6 шт",
        description: "Сыр моцарелла в хрустящей панировке.",
        details: "450 ккал · 15-20 мин",
        accent: "fries",
        emoji: "🧀",
      },
      {
        id: 505,
        title: "Комбо на двоих",
        price: 1190,
        meta: "2 пиццы + напиток",
        description: "Выгодный набор для компании.",
        details: "2200 ккал · 30-40 мин",
        accent: "combo-light",
        emoji: "🥤",
        badge: "Топ продаж",
      },
      {
        id: 506,
        title: "Брауни",
        price: 179,
        meta: "110 г",
        description: "Шоколадный десерт с мягкой серединой.",
        details: "320 ккал · 10-15 мин",
        accent: "coffee",
        emoji: "🍫",
      },
    ],
  },
  6: {
    categories: ["Все", "Салаты", "Супы", "Горячее", "Выпечка", "Напитки"],
    featuredProducts: [
      {
        id: 601,
        title: "Борщ со сметаной",
        price: 289,
        meta: "350 г",
        description: "Домашний борщ на говяжьем бульоне.",
        details: "290 ккал · 15-20 мин",
        accent: "combo-light",
        emoji: "🥣",
      },
      {
        id: 602,
        title: "Куриная котлета с пюре",
        price: 339,
        meta: "320 г",
        description: "Классический обед на каждый день.",
        details: "540 ккал · 15-20 мин",
        accent: "burger",
        emoji: "🍽️",
      },
      {
        id: 603,
        title: "Салат Цезарь",
        price: 319,
        meta: "220 г",
        description: "Курица гриль, айсберг и соус цезарь.",
        details: "410 ккал · 10-15 мин",
        accent: "combo",
        emoji: "🥗",
      },
    ],
    promoProducts: [
      {
        id: 604,
        title: "Эклер ванильный",
        price: 139,
        meta: "85 г",
        description: "Заварное пирожное с кремом.",
        details: "220 ккал · 10-15 мин",
        accent: "coffee",
        emoji: "🍮",
      },
      {
        id: 605,
        title: "Морс ягодный",
        price: 119,
        meta: "500 мл",
        description: "Натуральный морс без красителей.",
        details: "130 ккал · 10-15 мин",
        accent: "fries",
        emoji: "🧃",
      },
      {
        id: 606,
        title: "Пирог с капустой",
        price: 189,
        meta: "160 г",
        description: "Сытный пирог из печи.",
        details: "360 ккал · 15-20 мин",
        accent: "nuggets",
        emoji: "🥧",
      },
    ],
  },
  7: {
    categories: ["Все", "Кофе", "Холодные напитки", "Завтраки", "Десерты", "Сэндвичи"],
    featuredProducts: [
      {
        id: 701,
        title: "Латте большой",
        price: 219,
        meta: "400 мл",
        description: "Насыщенный кофе с молоком.",
        details: "230 ккал · 10-15 мин",
        accent: "coffee",
        emoji: "☕",
      },
      {
        id: 702,
        title: "Айс-кофе карамель",
        price: 239,
        meta: "400 мл",
        description: "Холодный кофе с карамельным сиропом.",
        details: "250 ккал · 10-15 мин",
        accent: "combo-light",
        emoji: "🧋",
      },
      {
        id: 703,
        title: "Сэндвич с индейкой",
        price: 289,
        meta: "210 г",
        description: "Тостовый хлеб, индейка и сыр.",
        details: "390 ккал · 15-20 мин",
        accent: "burger",
        emoji: "🥪",
      },
    ],
    promoProducts: [
      {
        id: 704,
        title: "Круассан миндальный",
        price: 179,
        meta: "120 г",
        description: "Слоеное тесто и миндальная начинка.",
        details: "360 ккал · 10-15 мин",
        accent: "combo",
        emoji: "🥐",
      },
      {
        id: 705,
        title: "Чизкейк манго",
        price: 249,
        meta: "130 г",
        description: "Десерт с тропическим вкусом.",
        details: "340 ккал · 10-15 мин",
        accent: "nuggets",
        emoji: "🍰",
      },
      {
        id: 706,
        title: "Матча-тоник",
        price: 209,
        meta: "350 мл",
        description: "Освежающий напиток на матче.",
        details: "140 ккал · 10-15 мин",
        accent: "fries",
        emoji: "🍵",
      },
    ],
  },
  8: {
    categories: ["Все", "Выпечка", "Хлеб", "Пироги", "Десерты", "Напитки"],
    featuredProducts: [
      {
        id: 801,
        title: "Круассан классический",
        price: 119,
        meta: "80 г",
        description: "Сливочное слоеное тесто.",
        details: "270 ккал · 10-15 мин",
        accent: "combo",
        emoji: "🥐",
      },
      {
        id: 802,
        title: "Багет французский",
        price: 99,
        meta: "250 г",
        description: "Хрустящая корочка и мягкий мякиш.",
        details: "620 ккал · 10-15 мин",
        accent: "fries",
        emoji: "🥖",
      },
      {
        id: 803,
        title: "Пирог с яблоком",
        price: 269,
        meta: "450 г",
        description: "Домашний пирог с яблочной начинкой.",
        details: "930 ккал · 20-30 мин",
        accent: "burger",
        emoji: "🥧",
      },
    ],
    promoProducts: [
      {
        id: 804,
        title: "Булочка с корицей",
        price: 129,
        meta: "95 г",
        description: "Ароматная выпечка с глазурью.",
        details: "310 ккал · 10-15 мин",
        accent: "nuggets",
        emoji: "🍥",
      },
      {
        id: 805,
        title: "Эклер шоколадный",
        price: 149,
        meta: "90 г",
        description: "Заварное пирожное с шоколадом.",
        details: "260 ккал · 10-15 мин",
        accent: "coffee",
        emoji: "🍫",
      },
      {
        id: 806,
        title: "Чай облепиховый",
        price: 169,
        meta: "400 мл",
        description: "Горячий чай с ягодами облепихи.",
        details: "120 ккал · 10-15 мин",
        accent: "combo-light",
        emoji: "🫖",
      },
    ],
  },
  101: {
    categories: ["Все", "Овощи и фрукты", "Молочка", "Напитки", "Готовая еда", "Акции"],
    featuredProducts: [
      {
        id: 10101,
        title: "Молоко 3.2%",
        price: 109,
        meta: "930 мл",
        description: "Пастеризованное молоко для завтрака и кофе.",
        details: "60 ккал / 100 мл · до 45 мин",
        accent: "coffee",
        emoji: "🥛",
      },
      {
        id: 10102,
        title: "Бананы",
        price: 129,
        meta: "1 кг",
        description: "Свежие бананы первой категории.",
        details: "89 ккал / 100 г · до 45 мин",
        accent: "combo-light",
        emoji: "🍌",
      },
      {
        id: 10103,
        title: "Салат Цезарь",
        price: 249,
        meta: "180 г",
        description: "Готовый салат в удобной упаковке.",
        details: "210 ккал · до 45 мин",
        accent: "combo",
        emoji: "🥗",
      },
    ],
    promoProducts: [
      {
        id: 10104,
        title: "Вода минеральная",
        price: 59,
        meta: "1.5 л",
        description: "Негазированная питьевая вода.",
        details: "0 ккал · до 45 мин",
        accent: "fries",
        emoji: "💧",
      },
      {
        id: 10105,
        title: "Хлеб тостовый",
        price: 79,
        meta: "400 г",
        description: "Нарезанный хлеб для сэндвичей.",
        details: "250 ккал / 100 г · до 45 мин",
        accent: "burger",
        emoji: "🍞",
      },
      {
        id: 10106,
        title: "Сыр гауда",
        price: 219,
        meta: "200 г",
        description: "Полутвердый сыр в нарезке.",
        details: "350 ккал / 100 г · до 45 мин",
        accent: "nuggets",
        emoji: "🧀",
        badge: "2 по цене 1",
      },
    ],
  },
  102: {
    categories: ["Все", "Свежие продукты", "Готовая еда", "Снеки", "Напитки", "Для дома"],
    featuredProducts: [
      {
        id: 10201,
        title: "Творог фермерский",
        price: 169,
        meta: "300 г",
        description: "Натуральный творог без добавок.",
        details: "140 ккал / 100 г · до 35 мин",
        accent: "combo-light",
        emoji: "🥣",
      },
      {
        id: 10202,
        title: "Смузи манго",
        price: 199,
        meta: "250 мл",
        description: "Фруктовый напиток без сахара.",
        details: "75 ккал / 100 мл · до 35 мин",
        accent: "coffee",
        emoji: "🥭",
      },
      {
        id: 10203,
        title: "Сэндвич с курицей",
        price: 229,
        meta: "190 г",
        description: "Готовый сэндвич для перекуса.",
        details: "260 ккал · до 35 мин",
        accent: "burger",
        emoji: "🥪",
      },
    ],
    promoProducts: [
      {
        id: 10204,
        title: "Ореховый микс",
        price: 249,
        meta: "150 г",
        description: "Ассорти из миндаля и кешью.",
        details: "560 ккал / 100 г · до 35 мин",
        accent: "nuggets",
        emoji: "🥜",
      },
      {
        id: 10205,
        title: "Йогурт греческий",
        price: 119,
        meta: "200 г",
        description: "Натуральный густой йогурт.",
        details: "95 ккал / 100 г · до 35 мин",
        accent: "fries",
        emoji: "🥛",
      },
      {
        id: 10206,
        title: "Эко-пакеты",
        price: 39,
        meta: "30 шт",
        description: "Плотные биоразлагаемые пакеты.",
        details: "Для дома · до 35 мин",
        accent: "combo",
        emoji: "🛍️",
      },
    ],
  },
  103: {
    categories: ["Все", "Премиум", "Сыры и мясо", "Готовая кухня", "Десерты", "Напитки"],
    featuredProducts: [
      {
        id: 10301,
        title: "Прошутто крудо",
        price: 489,
        meta: "100 г",
        description: "Итальянский сыровяленый окорок.",
        details: "250 ккал / 100 г · до 55 мин",
        accent: "nuggets",
        emoji: "🥓",
      },
      {
        id: 10302,
        title: "Сыр бри",
        price: 379,
        meta: "125 г",
        description: "Мягкий французский сыр.",
        details: "330 ккал / 100 г · до 55 мин",
        accent: "combo",
        emoji: "🧀",
      },
      {
        id: 10303,
        title: "Паста с лососем",
        price: 459,
        meta: "280 г",
        description: "Готовое блюдо от кулинарии.",
        details: "490 ккал · до 55 мин",
        accent: "burger",
        emoji: "🍝",
      },
    ],
    promoProducts: [
      {
        id: 10304,
        title: "Тирамису",
        price: 329,
        meta: "140 г",
        description: "Классический итальянский десерт.",
        details: "360 ккал · до 55 мин",
        accent: "coffee",
        emoji: "🍰",
      },
      {
        id: 10305,
        title: "Сок апельсиновый",
        price: 219,
        meta: "1 л",
        description: "Свежевыжатый сок в бутылке.",
        details: "45 ккал / 100 мл · до 55 мин",
        accent: "combo-light",
        emoji: "🍊",
      },
      {
        id: 10306,
        title: "Круассан миндальный",
        price: 199,
        meta: "1 шт",
        description: "Выпечка из собственной пекарни.",
        details: "340 ккал · до 55 мин",
        accent: "fries",
        emoji: "🥐",
        badge: "Новинка",
      },
    ],
  },
  104: {
    categories: ["Все", "Быстрые покупки", "Напитки", "Снеки", "Молочка", "Товары дома"],
    featuredProducts: [
      {
        id: 10401,
        title: "Вода без газа",
        price: 39,
        meta: "0.5 л",
        description: "Питьевая вода на каждый день.",
        details: "0 ккал · до 20 мин",
        accent: "fries",
        emoji: "💧",
      },
      {
        id: 10402,
        title: "Кефир 2.5%",
        price: 79,
        meta: "900 мл",
        description: "Свежий кефир от локального бренда.",
        details: "53 ккал / 100 мл · до 20 мин",
        accent: "coffee",
        emoji: "🥛",
      },
      {
        id: 10403,
        title: "Чипсы картофельные",
        price: 119,
        meta: "140 г",
        description: "Снэк с классическим вкусом.",
        details: "520 ккал / 100 г · до 20 мин",
        accent: "nuggets",
        emoji: "🥔",
      },
    ],
    promoProducts: [
      {
        id: 10404,
        title: "Шоколад молочный",
        price: 99,
        meta: "90 г",
        description: "Плитка молочного шоколада.",
        details: "540 ккал / 100 г · до 20 мин",
        accent: "combo",
        emoji: "🍫",
      },
      {
        id: 10405,
        title: "Хлеб нарезной",
        price: 59,
        meta: "350 г",
        description: "Свежий пшеничный хлеб.",
        details: "230 ккал / 100 г · до 20 мин",
        accent: "burger",
        emoji: "🍞",
      },
      {
        id: 10406,
        title: "Салфетки бумажные",
        price: 69,
        meta: "100 шт",
        description: "Мягкие двухслойные салфетки.",
        details: "Товары дома · до 20 мин",
        accent: "combo-light",
        emoji: "🧻",
      },
    ],
  },
  105: {
    categories: ["Все", "Фрукты", "Ягоды", "Наборы", "Сухофрукты", "Акции"],
    featuredProducts: [
      {
        id: 10501,
        title: "Клубника свежая",
        price: 349,
        meta: "500 г",
        description: "Сладкая ягода в сезонной поставке.",
        details: "33 ккал / 100 г · до 30 мин",
        accent: "combo",
        emoji: "🍓",
      },
      {
        id: 10502,
        title: "Манго спелое",
        price: 229,
        meta: "1 шт",
        description: "Ароматный фрукт, готов к употреблению.",
        details: "60 ккал / 100 г · до 30 мин",
        accent: "burger",
        emoji: "🥭",
      },
      {
        id: 10503,
        title: "Голубика",
        price: 289,
        meta: "250 г",
        description: "Свежая голубика для завтраков и десертов.",
        details: "57 ккал / 100 г · до 30 мин",
        accent: "nuggets",
        emoji: "🫐",
      },
    ],
    promoProducts: [
      {
        id: 10504,
        title: "Фруктовый набор",
        price: 599,
        meta: "1 кг",
        description: "Яблоки, бананы, груши и киви.",
        details: "Набор · до 30 мин",
        accent: "combo-light",
        emoji: "🍍",
        badge: "Скидка 15%",
      },
      {
        id: 10505,
        title: "Курага",
        price: 219,
        meta: "300 г",
        description: "Натуральная курага без сахара.",
        details: "240 ккал / 100 г · до 30 мин",
        accent: "fries",
        emoji: "🥭",
      },
      {
        id: 10506,
        title: "Изюм темный",
        price: 179,
        meta: "250 г",
        description: "Сладкий изюм для выпечки.",
        details: "280 ккал / 100 г · до 30 мин",
        accent: "coffee",
        emoji: "🍇",
      },
    ],
  },
};

const getExtraProducts = (id) => {
  const numericId = Number(id);
  const isStore = numericId >= 101;

  if (isStore) {
    return {
      featuredProducts: [
        {
          id: numericId * 1000 + 1,
          title: "Ореховый батончик",
          price: 89,
          meta: "45 г",
          description: "Быстрый перекус с орехами и медом.",
          details: "Снеки · до 35 мин",
          category: "Снеки",
          accent: "nuggets",
          emoji: "🍫",
          badge: "Новинка",
        },
      ],
      promoProducts: [
        {
          id: numericId * 1000 + 2,
          title: "Сок яблочный",
          price: 119,
          meta: "1 л",
          description: "Натуральный яблочный сок без газа.",
          details: "Напитки · до 35 мин",
          category: "Напитки",
          accent: "combo-light",
          emoji: "🧃",
        },
      ],
    };
  }

  return {
    featuredProducts: [
      {
        id: numericId * 1000 + 1,
        title: "Цезарь ролл",
        price: 219,
        meta: "210 г",
        description: "Курица, салат и соус цезарь в тортилье.",
        details: "Популярное · 15-20 мин",
        category: "Популярное",
        accent: "burger",
        emoji: "🌯",
        badge: "Новинка",
      },
    ],
    promoProducts: [
      {
        id: numericId * 1000 + 2,
        title: "Лимонад домашний",
        price: 149,
        meta: "400 мл",
        description: "Освежающий лимонад с цитрусом.",
        details: "Напитки · 10-15 мин",
        category: "Напитки",
        accent: "coffee",
        emoji: "🍋",
      },
    ],
  };
};

export const getRestaurantPageData = (id) => {
  const pageData = restaurantPageDataById[id] || defaultPageData;
  const extraProducts = getExtraProducts(id);

  return {
    ...pageData,
    featuredProducts: [...pageData.featuredProducts, ...extraProducts.featuredProducts],
    promoProducts: [...pageData.promoProducts, ...extraProducts.promoProducts],
  };
};
