export const homeBanners = [
  {
    id: "hot",
    title: "Горячо. Быстро. Вкусно.",
    accent: "warm",
    emoji: "🥐",
  },
  {
    id: "delivery",
    title: "-50% доставка",
    accent: "dark",
    emoji: "🍜",
  },
  {
    id: "sale",
    title: "Скидки. SALE%",
    accent: "soft",
    emoji: "🛍️",
  },
];

export const homeCategories = [
  "Все",
  "Бургеры",
  "Суши",
  "Пицца",
  "Кафе",
  "Паста",
  "Завтраки",
  "Обеды",
];

export const homeSortOptions = [
  {
    id: "default",
    title: "По умолчанию",
  },
  {
    id: "fast",
    title: "Быстрее",
  },
  {
    id: "cheap",
    title: "Дешевле",
  },
  {
    id: "rating",
    title: "Рейтинг",
  },
];

export const homeRestaurants = [
  {
    id: 1,
    title: "Вкусно - и точка",
    rating: "4.5",
    time: "45 - 55 мин",
    accent: "green",
    emoji: "🍔",
    note: "Грандиозно вкусно",
    price: "от 189 ₽",
    minPrice: 189,
    deliveryMinutes: 45,
    ratingValue: 4.5,
    categories: ["Бургеры", "Завтраки", "Обеды"],
  },
  {
    id: 2,
    title: "Бургер Кинг",
    rating: "4.2",
    time: "35 - 45 мин",
    accent: "orange",
    emoji: "🍔",
    label: "доставка 0Р",
    price: "от 159 ₽",
    minPrice: 159,
    deliveryMinutes: 35,
    ratingValue: 4.2,
    categories: ["Бургеры", "Обеды"],
  },
  {
    id: 3,
    title: "Шоколадница",
    rating: "4.8",
    time: "25 - 35 мин",
    accent: "brown",
    emoji: "🥪",
    note: "50%",
    price: "от 210 ₽",
    minPrice: 210,
    deliveryMinutes: 25,
    ratingValue: 4.8,
    categories: ["Кафе", "Завтраки", "Обеды"],
  },
  {
    id: 4,
    title: "Суши Пицца Wok",
    rating: "4.0",
    time: "60 - 70 мин",
    accent: "gray",
    emoji: "🍣",
    price: "от 249 ₽",
    minPrice: 249,
    deliveryMinutes: 60,
    ratingValue: 4.0,
    categories: ["Суши", "Пицца", "Паста"],
  },
  {
    id: 5,
    title: "Папа Джонс",
    rating: "4.1",
    time: "55 - 65 мин",
    accent: "red",
    emoji: "🍕",
    price: "от 399 ₽",
    minPrice: 399,
    deliveryMinutes: 55,
    ratingValue: 4.1,
    categories: ["Пицца"],
  },
  {
    id: 6,
    title: "Братья Караваевы",
    rating: "4.7",
    time: "40 - 50 мин",
    accent: "cream",
    emoji: "🥗",
    label: "доставка 0Р",
    price: "от 179 ₽",
    minPrice: 179,
    deliveryMinutes: 40,
    ratingValue: 4.7,
    categories: ["Кафе", "Паста", "Завтраки", "Обеды"],
  },
  {
    id: 7,
    title: "Coffee City",
    rating: "4.6",
    time: "20 - 30 мин",
    accent: "coffee-shop",
    emoji: "☕",
    note: "кофе + десерт",
    price: "от 129 ₽",
    minPrice: 129,
    deliveryMinutes: 20,
    ratingValue: 4.6,
    categories: ["Кафе", "Завтраки"],
  },
  {
    id: 8,
    title: "Пекарня рядом",
    rating: "4.9",
    time: "25 - 35 мин",
    accent: "bakery",
    emoji: "🥐",
    label: "свежая выпечка",
    price: "от 89 ₽",
    minPrice: 89,
    deliveryMinutes: 25,
    ratingValue: 4.9,
    categories: ["Кафе", "Завтраки"],
  },
];

export const homeMarkets = [
  {
    id: 101,
    title: "Перекресток",
    rating: "4.6",
    time: "60 - 70 мин",
    accent: "market-green",
    emoji: "🛒",
    subtitle: "Скидка",
    price: "от 600 ₽",
  },
  {
    id: 102,
    title: "Вкусвилл",
    rating: "4.5",
    time: "50 - 60 мин",
    accent: "market-bright",
    emoji: "🥬",
    subtitle: "Общественная доставка бесплатно",
    label: "доставка 0Р",
    price: "от 450 ₽",
  },
  {
    id: 103,
    title: "Азбука вкуса",
    rating: "4.7",
    time: "45 - 55 мин",
    accent: "market-dark",
    emoji: "🌿",
    price: "от 900 ₽",
  },
  {
    id: 104,
    title: "Минимаркет 24",
    rating: "4.3",
    time: "30 - 40 мин",
    accent: "market-blue",
    emoji: "🥛",
    subtitle: "Молоко, хлеб, вода",
    price: "от 350 ₽",
  },
  {
    id: 105,
    title: "Фруктовая лавка",
    rating: "4.8",
    time: "35 - 45 мин",
    accent: "market-fruit",
    emoji: "🍓",
    subtitle: "Фрукты и ягоды",
    label: "витаминный набор",
    price: "от 299 ₽",
  },
];

export const homeProducts = [
  {
    id: "p1",
    title: "Капучино и круассан",
    vendor: "Coffee City",
    price: 239,
    oldPrice: 299,
    weight: "300 мл + 1 шт",
    accent: "coffee",
    emoji: "☕",
  },
  {
    id: "p2",
    title: "Пицца Маргарита",
    vendor: "Папа Джонс",
    price: 499,
    weight: "30 см",
    accent: "pizza",
    emoji: "🍕",
  },
  {
    id: "p3",
    title: "Фруктовый набор",
    vendor: "Фруктовая лавка",
    price: 359,
    oldPrice: 420,
    weight: "1 кг",
    accent: "fruit",
    emoji: "🍓",
  },
  {
    id: "p4",
    title: "Готовый обед",
    vendor: "Братья Караваевы",
    price: 289,
    weight: "салат + горячее",
    accent: "lunch",
    emoji: "🍱",
  },
];
